version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: jaffle_shop
    ports:
      - "5431:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: